#!/bin/bash

set -e

if [ $# -le 0 ] ; then
    in=examples/basic/unformatted.pc
else
    in="$1"
fi

log=errors.txt
out=/dev/null

debug=debug/format/1
after=${debug}/after.pc

rm -rf ${debug}

( PYTHONPATH=$(realpath src) python3 -m proc_format --debug=${debug} ${in} ${out} 2>&1 ) | tee ${log}

if [ -r ${after} ] ; then
    cat ${after}
    echo
fi
