#!/bin/bash

set -e

if [ $# -le 0 ] ; then
    in=examples/basic/unformated.pc
else
    in="$1"
fi

log=/dn/errors.txt
out=debug/formated.pc

rm -f ${out}

( PYTHONPATH=$(realpath src) python -m proc_format ${in} ${out} 2>&1 ) | tee ${log}

if [ -r ${out} ] ; then
    cat ${out}
    echo
fi
