#!/bin/bash

( set -x && find . -name '*~' -delete )

( set -x && find . -name '*.vsix' -delete )

for cache in __pycache__ .pytest_cache ; do
    find . -name ${cache} | xargs -t -n 1 rm -rf
done

    
